ruby main.rb ../inputs/generated6/generated_cars_states_file1 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_1
ruby main.rb ../inputs/generated6/generated_cars_states_file2 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_2
ruby main.rb ../inputs/generated6/generated_cars_states_file3 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_3
ruby main.rb ../inputs/generated6/generated_cars_states_file4 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_4
ruby main.rb ../inputs/generated6/generated_cars_states_file5 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_5
ruby main.rb ../inputs/generated6/generated_cars_states_file6 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_6
ruby main.rb ../inputs/generated6/generated_cars_states_file7 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_7
ruby main.rb ../inputs/generated6/generated_cars_states_file8 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_8
ruby main.rb ../inputs/generated6/generated_cars_states_file9 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_9
ruby main.rb ../inputs/generated6/generated_cars_states_file10 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_10
ruby main.rb ../inputs/generated6/generated_cars_states_file11 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_11
ruby main.rb ../inputs/generated6/generated_cars_states_file12 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_12
ruby main.rb ../inputs/generated6/generated_cars_states_file13 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_13
ruby main.rb ../inputs/generated6/generated_cars_states_file14 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_14
ruby main.rb ../inputs/generated6/generated_cars_states_file15 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_15
ruby main.rb ../inputs/generated6/generated_cars_states_file16 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_16
ruby main.rb ../inputs/generated6/generated_cars_states_file17 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_17
ruby main.rb ../inputs/generated6/generated_cars_states_file18 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_18
ruby main.rb ../inputs/generated6/generated_cars_states_file19 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_19
ruby main.rb ../inputs/generated6/generated_cars_states_file20 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_20
ruby main.rb ../inputs/generated6/generated_cars_states_file21 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_21
ruby main.rb ../inputs/generated6/generated_cars_states_file22 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_22
ruby main.rb ../inputs/generated6/generated_cars_states_file23 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_23
ruby main.rb ../inputs/generated6/generated_cars_states_file24 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_24
ruby main.rb ../inputs/generated6/generated_cars_states_file25 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_25
ruby main.rb ../inputs/generated6/generated_cars_states_file26 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_26
ruby main.rb ../inputs/generated6/generated_cars_states_file27 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_27
ruby main.rb ../inputs/generated6/generated_cars_states_file28 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_28
ruby main.rb ../inputs/generated6/generated_cars_states_file29 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_29
ruby main.rb ../inputs/generated6/generated_cars_states_file30 ../inputs/sl_roads_file > ../../statistics_output/cars_nr_6_case_30
